name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        repository: github.com/exactpro-th2/ci-github-action
        ref: test
        token: ${{ secrets.PAT_CI_ACTION }}
    - name: Run the action
      uses: ./
      with:
        ref: ${{ github.ref }}
