name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Checkout tool
      uses: actions/checkout@v2
      with:
        repository: exactpro-th2/ci-github-action
        ref: test
        token: ${{ secrets.PAT_CI_ACTION }}
        path: ci-github-action
    - name: Run CI action
      uses: ./ci-github-action
      with:
        ref: ${{ github.ref }}
