name: Build and publish Python distributions to PyPI

on:
  push:


jobs:
  build-n-publish:
    name: Build ${{ matrix.proto }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        proto:
          - codec-fast
          - codec-fix
          - codec-itch
          - codec-ntg
          - codec-tcpip

    steps:
    - name: Set up Python 3.7
      run: echo ${{ matrix.proto }}
