name: Build and publish Python distributions to PyPI

on:
  push:
    branches:
    - 'master'
    paths:
    - 'package_info.json'

jobs:
  build-n-publish:
    name: Build and Python distributions to PyPI
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
