name: Build and publish Python distributions to PyPI

on:
  push:


jobs:
  build-n-publish:
    name: Build and Python distributions to PyPI
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [6, 8, 10]
    steps:
    - name: Set up Python 3.7
      run: echo ${{ matrix.os }}-${{ matrix.node }}
